# Define all apps here
DJANGO_APP = [
    'apps.users.apps.UsersConfig',
    'apps.login',
    'apps.dashboard',
    'apps.cms_pages',
    'apps.email_templates',
    'apps.email_logs',
    'apps.settings',
    'apps.faq',
    'apps.api',
    'apps.permissions',
    'apps.languages',
    # 'apps.masters',
    # 'apps.patient_management',
    # 'apps.doctor_management',
    # 'apps.category_management',
    # 'apps.hospitals_management',
    # 'apps.clinic_management',
    # 'apps.pharmacy_management',
    # 'apps.diagnostic_management',
    # 'apps.image_slider',
    # 'apps.blogs',
    # 'apps.booking',
    # 'apps.tips_tweet',
    # 'apps.testimonial',
    # 'apps.favourite',
    # 'apps.review',
    'drf_yasg',
]
