# Generated by Django 3.2.18 on 2023-07-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('value', models.TextField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('input_type', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('editable', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
    ]
