# Generated by Django 3.2.18 on 2023-07-12 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('path', models.CharField(blank=True, max_length=250, null=True)),
                ('segment', models.CharField(blank=True, max_length=250, null=True)),
                ('module_order', models.PositiveIntegerField(blank=True, null=True)),
                ('icon', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='permissions.adminmodule')),
            ],
            options={
                'db_table': 'admin_modules',
            },
        ),
        migrations.CreateModel(
            name='AdminModuleAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('function_name', models.CharField(blank=True, max_length=250, null=True)),
                ('is_show', models.BooleanField(blank=True, default=True, null=True)),
                ('admin_module_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='permissions.adminmodule')),
            ],
            options={
                'db_table': 'admin_modules_actions',
            },
        ),
    ]
